//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedbacks
    {
        public int Id { get; set; }
        public int UsersId { get; set; }
        [Display(Name = "Feedback")]
        [DataType(DataType.MultilineText)]
        public string Feedback { get; set; }
    }
}
