//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JamesThewDOTcomEntities : DbContext
    {
        public JamesThewDOTcomEntities()
            : base("name=JamesThewDOTcomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subscription_Type> Subscription_Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Annoucments> Annoucments { get; set; }
        public virtual DbSet<Contests> Contests1 { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Feedbacks> Feedbacks { get; set; }
        public virtual DbSet<Recipes> Recipes1 { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
        public virtual DbSet<Recipe_Feedback> Recipe_Feedback { get; set; }
    }
}
