//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tips
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public int UsersId { get; set; }
    
        public virtual Users User { get; set; }
    }
}
